<script setup lang="ts">
import { ref } from 'vue';
import { useRouter } from 'vue-router';
import apiClient from '@/api/axios'; // 假設你的 axios 實例位置
import { useAuthStore } from '@/stores/auth';

const router = useRouter();
const authStore = useAuthStore();

// UI 狀態控制
const step = ref<1 | 2 | 3>(1); // 1: 初始, 2: 掃描與輸入, 3: 成功
const isLoading = ref(false);
const errorMsg = ref('');

// 資料暫存
const qrCodeUrl = ref('');
const secretKey = ref('');
const verificationCode = ref('');

/**
 * Step 1 -> Step 2: 呼叫後端產生 Secret & QR Code
 */
const startSetup = async () => {
  isLoading.value = true;
  errorMsg.value = '';
  
  try {
    // 注意：這裡的路徑取決於你的 Controller 前綴，假設是 /api/auth/2fa/generate
    // 如果你的 Controller 沒有 auth 前綴，請改為 /api/2fa/generate
    const res = await apiClient.post('/api/auth/2fa/generate');
    
    // 假設後端回傳格式為 { secret: string, qrCode: string (DataURI) }
    // 如果後端是用 otplib，通常會回傳這兩個欄位
    secretKey.value = res.data.secret;
    qrCodeUrl.value = res.data.qr; // 必須是 data:image/png;base64,... 格式
    
    step.value = 2;
  } catch (err: any) {
    console.error('Failed to generate 2FA:', err);
    errorMsg.value = err.response?.data?.message || 'Cannot generate 2FA setup, please try again later.';
  } finally {
    isLoading.value = false;
  }
};

/**
 * Step 2 -> Step 3: 送出驗證碼啟用 2FA
 */
const verifyAndEnable = async () => {
  if (!verificationCode.value || verificationCode.value.length !== 6) {
    errorMsg.value = 'Please enter a 6-digit verification code';
    return;
  }

  isLoading.value = true;
  errorMsg.value = '';

  try {
    await apiClient.post('/api/auth/2fa/enable', {
      code: verificationCode.value
    });

    step.value = 3;
    // 如果 store 有紀錄 user 狀態，可以在這裡更新，例如：
    authStore.set2FAEnabled(true); 
  } catch (err: any) {
    console.error('Failed to enable 2FA:', err);
    errorMsg.value = 'Verification code is incorrect or expired, please try again.';
  } finally {
    isLoading.value = false;
  }
};

/**
 * 完成後返回 Dashboard
 */
const finishSetup = () => {
  
  router.push('/student/dashboard');
};

/**
 * 複製密鑰到剪貼簿 (UX 優化)
 */
const copySecret = () => {
  navigator.clipboard.writeText(secretKey.value);
  alert('Secret key copied to clipboard!');
};
</script>

<template>
  <div class="auth-wrapper">
    <div class="auth-card">
      <header class="card-header">
        <div class="icon-shield">🛡️</div>
        <h2>Two-Factor Authentication (2FA) Setup</h2>
      </header>

      <div v-if="errorMsg" class="error-banner">
        {{ errorMsg }}
      </div>

      <div v-if="step === 1" class="step-content">
        <p class="description">
          Enabling two-factor authentication significantly enhances your account security.
          <br>After setup, you will need to enter a verification code generated by Google Authenticator in addition to your password when logging in.
        </p>
        <button class="btn-primary" @click="startSetup" :disabled="isLoading">
          {{ isLoading ? 'Processing...' : 'Start Setup' }}
        </button>
        <button class="btn-text" @click="router.back()">Maybe Later</button>
      </div>

      <div v-else-if="step === 2" class="step-content">
        <div class="qr-section">
          <p class="instruction">1. Please use Google Authenticator to scan the QR Code below</p>
          
          <div class="qr-img-wrapper">
            <img v-if="qrCodeUrl" :src="qrCodeUrl" alt="2FA QR Code" />
            <div v-else class="loading-placeholder">Loading...</div>
          </div>

          <div class="secret-text">
            <span>Or manually enter the secret key:</span>
            <code @click="copySecret" title="Click to copy">{{ secretKey }}</code>
          </div>
        </div>

        <div class="input-section">
          <p class="instruction">2. Enter the 6-digit verification code from the app</p>
          <input 
            v-model="verificationCode" 
            type="text" 
            maxlength="6" 
            placeholder="000 000" 
            class="code-input"
            @keyup.enter="verifyAndEnable"
          />
        </div>

        <div class="action-buttons">
          <button class="btn-primary" @click="verifyAndEnable" :disabled="isLoading">
            {{ isLoading ? 'Verifying...' : 'Enable Protection' }}
          </button>
          <button class="btn-secondary" @click="step = 1" :disabled="isLoading">
            Previous
          </button>
        </div>
      </div>

      <div v-else-if="step === 3" class="step-content success-step">
        <div class="success-icon">✅</div>
        <h3>Setup Complete!</h3>
        <p>Your account is now protected by two-factor authentication.</p>
        <button class="btn-primary" @click="finishSetup">
          Back to Dashboard
        </button>
      </div>

    </div>
  </div>
</template>

<style scoped>
.auth-wrapper {
  min-height: 100vh;
  display: flex;
  justify-content: center;
  align-items: center;
  background-color: #f3f4f6;
  padding: 1rem;
}

.auth-card {
  background: white;
  width: 100%;
  max-width: 480px;
  padding: 2.5rem;
  border-radius: 16px;
  box-shadow: 0 10px 25px rgba(0, 0, 0, 0.05);
  text-align: center;
}

.card-header {
  margin-bottom: 2rem;
}

.icon-shield {
  font-size: 3rem;
  margin-bottom: 1rem;
}

.card-header h2 {
  font-size: 1.5rem;
  color: #1f2937;
  font-weight: 700;
}

.description {
  color: #6b7280;
  line-height: 1.6;
  margin-bottom: 2rem;
}

.instruction {
  font-size: 0.95rem;
  color: #374151;
  margin-bottom: 0.5rem;
  font-weight: 500;
  text-align: left;
}

/* QR Code */
.qr-section {
  background: #f9fafb;
  padding: 1.5rem;
  border-radius: 12px;
  margin-bottom: 1.5rem;
}

.qr-img-wrapper {
  background: white;
  padding: 1rem;
  display: inline-block;
  border-radius: 8px;
  margin: 1rem 0;
  box-shadow: 0 2px 8px rgba(0,0,0,0.05);
}

.qr-img-wrapper img {
  width: 150px;
  height: 150px;
  object-fit: contain;
}

.secret-text {
  font-size: 0.85rem;
  color: #6b7280;
}

.secret-text code {
  background: #e5e7eb;
  padding: 0.2rem 0.5rem;
  border-radius: 4px;
  color: #111827;
  font-family: monospace;
  cursor: pointer;
  transition: background 0.2s;
}

.secret-text code:hover {
  background: #d1d5db;
}

/* Input */
.input-section {
  margin-bottom: 2rem;
  text-align: left;
}

.code-input {
  width: 100%;
  padding: 0.75rem;
  font-size: 1.5rem;
  text-align: center;
  letter-spacing: 0.5rem;
  border: 2px solid #e5e7eb;
  border-radius: 8px;
  transition: border-color 0.2s;
}

.code-input:focus {
  border-color: #4ade80;
  outline: none;
}

/* Buttons */
.btn-primary {
  width: 100%;
  padding: 0.8rem;
  background-color: #111827;
  color: white;
  border: none;
  border-radius: 8px;
  font-size: 1rem;
  cursor: pointer;
  font-weight: 600;
  transition: background 0.2s;
  margin-bottom: 1rem;
}

.btn-primary:hover:not(:disabled) {
  background-color: #000;
}

.btn-primary:disabled {
  background-color: #9ca3af;
  cursor: not-allowed;
}

.btn-secondary {
  width: 100%;
  padding: 0.8rem;
  background: white;
  border: 1px solid #d1d5db;
  color: #374151;
  border-radius: 8px;
  cursor: pointer;
  font-weight: 600;
}

.btn-text {
  background: none;
  border: none;
  color: #6b7280;
  cursor: pointer;
  text-decoration: underline;
  margin-top: 0.5rem;
}

/* Error & Success */
.error-banner {
  background-color: #fee2e2;
  color: #b91c1c;
  padding: 0.75rem;
  border-radius: 8px;
  margin-bottom: 1.5rem;
  font-size: 0.9rem;
}

.success-icon {
  font-size: 4rem;
  margin-bottom: 1rem;
}

.success-step h3 {
  font-size: 1.5rem;
  margin-bottom: 0.5rem;
}

.success-step p {
  color: #6b7280;
  margin-bottom: 2rem;
}
</style>